#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

PASS=true

REPO_PATH=$(git rev-parse --show-toplevel)
pushd "$REPO_PATH/app-devops-task"

for FILE in $STAGED_GO_FILES
do
  go vet ../$FILE
  if [[ $? != 0 ]]; then
    PASS=false
  fi
done

if ! $PASS; then
  printf "COMMIT FAILED\n"
  exit 1
else
  printf "COMMIT SUCCEEDED\n"
fi

exit 0